name = "employee-insights-api"
main = "build/worker/shim.mjs"
compatibility_date = "2023-12-01"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[d1_databases]]
binding = "DB"
database_name = "employee-insights"
database_id = "1bb5e7b7-3a9c-4db0-b47d-932a475b13a8"

[vars]
ENVIRONMENT = "production" 